import { Reservation } from "./types";
import { addDays, formatDateKey } from "./time";

export function createInitialReservations(today: Date): Reservation[] {
  const todayKey = formatDateKey(today);
  const tomorrowKey = formatDateKey(addDays(today, 1));

  return [
    {
      id: "seed-1",
      roomId: "400",
      date: todayKey,
      startTime: "10:00",
      endTime: "11:00",
      title: "週次定例",
      organizer: "田中 太郎",
      attendees: 5,
    },
    {
      id: "seed-2",
      roomId: "400",
      date: todayKey,
      startTime: "14:00",
      endTime: "15:00",
      title: "パートナー打合せ",
      organizer: "佐藤 美咲",
      attendees: 4,
    },
    {
      id: "seed-3",
      roomId: "408",
      date: todayKey,
      startTime: "09:30",
      endTime: "10:30",
      title: "プロジェクトキックオフ",
      organizer: "鈴木 拓真",
      attendees: 8,
    },
    {
      id: "seed-4",
      roomId: "408",
      date: todayKey,
      startTime: "13:00",
      endTime: "14:30",
      title: "採用面接",
      organizer: "高橋 大輔",
      attendees: 3,
    },
    {
      id: "seed-5",
      roomId: "415",
      date: todayKey,
      startTime: "11:00",
      endTime: "11:30",
      title: "1on1",
      organizer: "山田 智也",
      attendees: 2,
    },
    {
      id: "seed-6",
      roomId: "415",
      date: todayKey,
      startTime: "16:00",
      endTime: "16:30",
      title: "1on1",
      organizer: "中村 優子",
      attendees: 2,
    },
    {
      id: "seed-7",
      roomId: "414",
      date: todayKey,
      startTime: "09:00",
      endTime: "09:30",
      title: "朝会",
      organizer: "小林 玲奈",
      attendees: 4,
    },
    {
      id: "seed-8",
      roomId: "423",
      date: todayKey,
      startTime: "15:00",
      endTime: "17:00",
      title: "全社会議リハーサル",
      organizer: "松本 結衣",
      attendees: 10,
    },
    {
      id: "seed-9",
      roomId: "408",
      date: tomorrowKey,
      startTime: "10:00",
      endTime: "11:30",
      title: "月次経営会議",
      organizer: "高橋 大輔",
      attendees: 9,
    },
    {
      id: "seed-10",
      roomId: "423",
      date: tomorrowKey,
      startTime: "13:00",
      endTime: "14:00",
      title: "来客対応(A社様)",
      organizer: "田中 太郎",
      attendees: 6,
    },
  ];
}
